.travis.yml, src/main.rs
=> Check db and theme consistency

config/filetypes.yml
=> Added macos category to unimportant files

README.md
related to this issue https://github.com/sharkdp/vivid/issues/25
=> add macOS install instructions

CHANGELOG.md, src/main.rs
=> Do not panic if stdout is closed

README.md, themes/lava.yml
Hey, here is the theme I've been using the past months, I thought I would share it and might even have the chance to get some feedback
original file: https://github.com/fredericrous/dotfiles/blob/main/private_dot_config/vivid/themes/lava.yml
=> Add Lava theme

config/filetypes.yml
=> Add .webm media extension

config/filetypes.yml
See https://stackoverflow.com/a/8822377 for details.
=> Add Python .pyd and .pyo extensions

README.md
=> Add install instructions for Gentoo users

themes/dracula.yml
=> Dracula theme

themes/dracula.yml
This is to match new https://github.com/dracula/dircolors thingy
=> Update some bits

themes/alabaster_dark.yml
https://github.com/tonsky/sublime-scheme-alabaster
=> Add alabaster dark theme

themes/catppuccin-frappe.yml, themes/catppuccin-latte.yml, themes/catppuccin-macchiato.yml, themes/catppuccin-mocha.yml
Added all 4 Palettes of Catppuccin
https://github.com/catppuccin/catppuccin
=> feat(themes): add catppuccin

config/filetypes.yml
Hello. I hope this pull request finds you well. I thought I should add some more file types and filenames to your database. I would also like to contribute a theme at some point. Please tell me if you feel positively about my changes.
=> Adding more file types

themes/zenburn.yml
=> zenburn theme

themes/rose-pine-dawn.yml, themes/rose-pine-moon.yml, themes/rose-pine.yml
=> Add Rosé Pine theme

config/filetypes.yml
[AVIF](https://en.wikipedia.org/wiki/AVIF) is an newer image format being adopted by many.
=> Add `.avif` to image filetype

config/filetypes.yml
Add the [hare](https://harelang.org/) extension.
=> Add `.ha` to filetypes.yml

themes/modus-vivendi.yml
There is already modus-operandi, but, for dark terminals, modus-vivendi is nice to have as well.
=> added modus-vivendi theme

config/filetypes.yml
This adds the various [Aseprite](https://www.aseprite.org) file extensions: https://www.aseprite.org/docs/files/
=> Add Aseprite file extensions

config/filetypes.yml
=> Vim: add .swo and .swn for swap files
