- config/filetypes.yml
in various places.
This includes the LLVM textual IR (.ll), generated bitcode files (.bc),
a custom language used in LLVM's implementation called "TableGen" (.td),
and C++ extensions used for generated code and X-macro files (.def and
.inc).
Bitcode files are treated similarly to object files, although that is
a bit odd. They are somewhere between archives and object files in terms
of utility, but they most often show up as intermediate files. When
being packaged and used, they are more commonly placed into an archive,
so this seems the least confusing scheme to me.
> Add LLVM file types and extensions as well as extensions used by LLVM

- themes/jellybeans.yml
Based on the colors in the Vim theme here:
https://github.com/nanotech/jellybeans.vim
Yaml file based on the molokai one in the tree.
I've tried to use a fairly sensible palette to keep similar things in
similar color spectrums. Text is green, code is blue, markup is blue
green, etc. That said, I'm not an artist or a color person, so happy to
have suggestions on better arrangements here. I'm mostly trying to gain
some consistency in pallette across Vim and other tools.
> Add a Jellybeans inspired theme (dark, colorful).

- config/filetypes.yml
Fixed a typo in `config/filetypes.yml`, changing `INSTALL.md.txt` to `INSTALL.txt`.
> Fix INSTALL.txt

- config/filetypes.yml
Image filetypes:
Added .eps (Encapsulated PostScript) - https://fileinfo.com/extension/eps
Added .psd (Adobe Photoshop Document) - https://fileinfo.com/extension/psd
Added .tiff (alternative extension to Tagged Image File Format) - https://fileinfo.com/extension/tiff
Audio filetypes:
Added .m4a (MPEG-4 Audio File) - https://fileinfo.com/extension/m4a
> Add more media file types

- Cargo.lock
- Cargo.toml
- src/main.rs
Here's a potential solution to #25. I copied what I could from bat here:
https://github.com/sharkdp/bat/blob/62014c1094470833b2b72179d3f1bf7f803404e3/src/bin/bat/directories.rs#L18-L27 
The challenge was returning a `PathBuf` rather than an `Option<PathBuf>`
I'm still getting the hang of Rust, so I'm not 100% sure on the style—corrections much appreciated!
> Add XDG_CONFIG_HOME as possible source for theme files

- Cargo.lock
- Cargo.toml
- src/error.rs
- src/filetypes.rs
- src/main.rs
- src/theme.rs
Building on #25, here's a sample of how we can embed the theme and filetypes files into the executable.
> Sample implementation of embedding theme files

- README.md
1. Add a note about using `LS_COLORS` with MacOS, as this tripped me up for a while. 
I used the suggestion from https://github.com/sharkdp/vivid/issues/25, which worked for me.
> Note MacOS ls in README

- src/error.rs
- src/main.rs
- src/util.rs
Possibly resolves #46 (not entirely sure what the ask is), or at the very least hopefully adds some useful functionality. 
The goal is to display to users which themes are available to use, so that they have an idea of what can be run into `preview` or `generate`.
Output
```
> ./target/debug/vivid themes
ayu
jellybeans
molokai
snazzy
solarized-light
solarized-dark
```
> Subcommand to list out available themes

- themes/one-dark.yml
- themes/one-light.yml
Signed-off-by: mortezadadgar <mortezadadgar97@gmail.com>
> Add One theme

- themes/nord.yml
Hi! I've been using `vivid` for a while and I love it. I've been recently moving my stuff to use the [Nord](https://www.nordtheme.com/) color scheme, and just made one for vivid. I'm using this personally, but since it's a fairly popular and well-known theme, I figured I'd send this your way.
Feel free to reject it if you'd rather not have it, but I saw that others have contributed well-known themes before.
> Add a Nord theme

- config/filetypes.yml
Add extensions for [Opus ](https://en.wikipedia.org/wiki/Opus_(audio_format)) and [WavPack](https://en.wikipedia.org/wiki/WavPack) audio formats.
> Add Opus and WavPack audio extensions

- config/filetypes.yml
- themes/ayu.yml
- themes/iceberg-dark.yml
- themes/jellybeans.yml
- themes/lava.yml
- themes/molokai.yml
- themes/nord.yml
- themes/one-dark.yml
- themes/one-light.yml
- themes/snazzy.yml
- themes/solarized-dark.yml
- themes/solarized-light.yml
* Reorder core filetypes as displayed by: `dircolors --print-database`
* Add new core filetypes:
* reset_to_normal
* multi_hard_link
* door
* setuid
* setgid
Closes: https://github.com/sharkdp/vivid/pull/39
> feat: Update filtetypes

- themes/gruvbox-dark-hard.yml
- themes/gruvbox-dark-soft.yml
- themes/gruvbox-dark.yml
- themes/gruvbox-light-hard.yml
- themes/gruvbox-light-soft.yml
- themes/gruvbox-light.yml
Filetype mapping heavily inspired/based on #39 with some touches.
Files were generated by a [ruby script][] using gruvbox colors table:
* https://github.com/gruvbox-community/gruvbox-contrib/blob/5be530c3bcde7f226324ec7974bd1a40a61a59d8/color.table
Colour table to palette mapping can be found here:
* https://gitlab.com/ixti/gruvbox-themes-generator/-/blob/master/palette.yml
Theme template:
* https://gitlab.com/ixti/gruvbox-themes-generator/-/blob/master/templates/vivid.yml
[ruby script]: https://gitlab.com/ixti/gruvbox-themes-generator/-/blob/master/generate
Closes: #76
> Add gruvbox theme

- src/main.rs
> Make the output order deterministic

- themes/lava.yml
was failing because of missing definitions
> fix lava theme

- themes/modus-operandi.yml
Hi, 
Here's a (quick) port of [modus operandi](https://protesilaos.com/emacs/modus-themes-pictures), an emacs theme. Screenshot below in nushell.
I could not figure how to integrate it into vivid search path unfortunately.
> Modus operandi theme

- Cargo.lock
- Cargo.toml
- src/main.rs
The config path is unchanged. The `etcetera` crate allows you to use the XDG spec on macOS too without any hassle. In addition, it is slightly smaller.
> Replace `dirs` crate with `etcetera` crate

- config/filetypes.yml
Typescript already has the `.tsx` filetype. We were missing the `.jsx` filetype for javascript.
> Add jsx filtype

- config/filetypes.yml
- project files `CHANGELOG{,.md,.txt}`, `CODE_OF_CONDUCT{,.md,.txt}`, `CONTRIBUTING{,.md,.txt}`
- Vlang files [`.v`, `v.mod`] (https://github.com/vlang/v)
- Golang files [`go.mod`, `go.sum`] (https://golangbyexample.com/go-mod-sum-module/)
- CI: `.cirrus.yml` (https://cirrus-ci.org/)
- Mac: `Icon\r` (Icon files for Finder, `\r` is necessary for it to work)
- editorconfig: `.editorconfig` (https://editorconfig.org/)
- other: `.ctags` (not very important, since they're always in a `.ctags.d/` dir)
> Add new filetypes

- Cargo.lock
- Cargo.toml
Hi,
This fix build on latest nightly for me:
```rust
$ cargo build
Compiling proc-macro2 v1.0.52
Compiling rust-embed-utils v7.5.0
error[E0635]: unknown feature `proc_macro_span_shrink`
--> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.52/src/lib.rs:92:30
```
ref. https://github.com/rust-lang/rust/issues/113152 fixed in proc-macro2 1.0.60
> bump rust-embed

- config/filetypes.yml
The additions are:
in text: special:
- FAQ (Frequently Asked Questions)
- LEGACY (information on legacy support or the like)
- NOTICE (important information that should be noticed)
- VERSION (version information)
in text: licenses:
- LICENCE (an alternative, but correct, spelling of LICENSE)
in markup: other:
- .1 (The format of man-pages on linux)
- .info (a GNU rich text format generated by GNU texinfo)
- .typ (source files for the typesetting program Typst)
in programming: source: cxx:
- .ino (source files for the Arduino platform, essentially extended C++)
in programming: source: shell:
- .nu (source files for the nu shell)
in programming: tooling: build:
- .mk (the same as .make)
in archives: other:
- .db (SQL, and possibly other, database files. bit unsure about the position for …
> Added multiple filetypes, explained in depth in the pull request

- themes/tokyonight-moon.yml
- themes/tokyonight-night.yml
- themes/tokyonight-storm.yml
This provides the **Moon**, **Night** and **Storm** (though not **Day**) variants of [Tokyo Night](https://github.com/folke/tokyonight.nvim). Closes #112.
> Add Tokyo Night theme

- config/filetypes.yml
- src/color.rs
- src/theme.rs
This patch allows the use of the colours: `black`, `red`, `green`, `yellow`, `blue`, `magenta`, `cyan`, `white`, `bright_black`, `bright_red`, `bright_green`, `bright_yellow`, `bright_blue`, `bright_magenta`, `bright_cyan`, `bright_white`, in any field which accepts a colour.  These will then be parsed as their [Ansi 3/4 bit equivalents](https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit).  I believe this makes a good addition to the program as some people (myself included), will prefer just to use the colours they've already defined in their terminal.  Further, this works better with some tools (e.g. `ranger`) which only support Ansi 3/4 or 256-colour, in which case the ansi 3/4 actually provides more accurate colours (given it is not quantized to the 256 palette, but rather …
> Added Ansi 3-bit Colors

- config/filetypes.yml
- src/font_style.rs
- src/main.rs
- src/theme.rs
This allows multiple `font_style`s to be used, allowing, say, for a bold and italic text. Fixes #49
All previous examples should work, but now you can also specify:
```yaml
font-style:
- bold
- underline
```
> Allowed font_style to be an array

- themes/nord.yml
> Update Nord theme to match reference implementation

- themes/tokyonight-day.yml
I added a light tokyonight theme (somewhat) based on tokyonight day from [tokyonight.nvim](https://github.com/folke/tokyonight.nvim). I didn't think too much about the meaning of the colors so I'm open for changes. I used the tokyonight-moon vivid theme as a base config file.
> Added tokyonight-day theme

- themes/dracula.yml
This change makes the Dracula theme's unimportant entry match Dracula's "Current Line" entry as `#44475A`. Before it was `#3A3C4E`, which isn't part of the Dracula palette.
See more: https://draculatheme.com/contribute
> dracula: Update `unimportant` to match Dracula colors
